line-length = 120

# use default method is ok

# [lint.mccabe]
# max-complexity = 10 # C901

# [lint.pyline]
# max-statements = 50 # PLR0915

[lint]
extend-select = ["C901", "PLR0915"]
ignore = [
    "SIM102", # SIM102推荐合并if，是错误的
]

# example: uv run ruff check entropy/domain/models --select UP006
