# currently, all config keys are hot reloaded
# 所有相对路径均以仓库根目录为基准（cwd）

# comfyui
comfyui_base_url: http://127.0.0.1:8188

# 工作流超时（秒）。如果不知道怎么设置，设置为正常执行时间的5倍即可。
workflow_timeout_seconds: 180

# 额外的有效标签，会热加载。文本文件，一行一个tag
extra_valid_tag_file: "" # entropy/conf/tag_datasets/extra_valid_tags.txt

# 服务监听端口
port: 5000
